-- Run this in the Supabase SQL editor to create and populate the techniques table

-- Techniques table
create table if not exists public.techniques (
  id integer primary key,
  name text not null,
  sport text not null check (sport in ('judo', 'bjj', 'both')),
  category text not null,
  description text,
  youtube_url text
);

-- Public read access (no auth required to browse the library)
alter table public.techniques enable row level security;

create policy "Anyone can read techniques"
  on public.techniques for select
  using (true);

-- Seed data from grapplingos_techniques - Techniques_v1.csv
insert into public.techniques (id, name, sport, category, description, youtube_url) values
(1, 'De-ashi-barai', 'judo', 'Throws', 'Forward foot sweep', 'https://www.youtube.com/watch?v=gW9LEvVmG2o'),
(2, 'Hiza-guruma', 'judo', 'Throws', 'Knee wheel', 'https://www.youtube.com/watch?v=a1RZvytW3OI'),
(3, 'Sasae-tsurikomi-ashi', 'judo', 'Throws', 'Propping drawing ankle throw', 'https://www.youtube.com/watch?v=MiGljHOokvE'),
(4, 'Uki-goshi', 'judo', 'Throws', 'Floating hip throw', 'https://www.youtube.com/watch?v=5jVF6r366Kg'),
(5, 'O-soto-gari', 'judo', 'Throws', 'Major outer reap', 'https://youtu.be/KeIPk8O58zs?si=PvMNCajz1evGAVif'),
(6, 'O-goshi', 'judo', 'Throws', 'Major hip throw', 'https://www.youtube.com/watch?v=VLYKx-Fwhxg'),
(7, 'O-uchi-gari', 'judo', 'Throws', 'Major inner reap', 'https://www.youtube.com/watch?v=I3BWf1ZoIuc'),
(8, 'Seoi-nage', 'judo', 'Throws', 'Shoulder throw', 'https://www.youtube.com/watch?v=eWEW9SfI5xg'),
(9, 'Ko-soto-gari', 'judo', 'Throws', 'Minor outer reap', 'https://www.youtube.com/watch?v=T3rSf8CcHg4'),
(10, 'Ko-uchi-gari', 'judo', 'Throws', 'Minor inner reap', 'https://www.youtube.com/watch?v=5E20xuzaXNw'),
(11, 'Koshi-guruma', 'judo', 'Throws', 'Hip wheel', 'https://www.youtube.com/watch?v=psG_Xx8NiIA'),
(12, 'Tsurikomi-goshi', 'judo', 'Throws', 'Lift-pull hip throw', 'https://www.youtube.com/watch?v=4HJumX7ArOI'),
(13, 'Okuri-ashi-harai', 'judo', 'Throws', 'Sliding foot sweep', 'https://www.youtube.com/watch?v=2WHtL7Rzwfs'),
(14, 'Tai-otoshi', 'judo', 'Throws', 'Body drop', 'https://www.youtube.com/watch?v=Q5kH1IIid-Q'),
(15, 'Harai-goshi', 'judo', 'Throws', 'Sweeping hip throw', 'https://www.youtube.com/watch?v=_gcIWtS-9Ms'),
(16, 'Uchi-mata', 'judo', 'Throws', 'Inner thigh throw', 'https://www.youtube.com/watch?v=N9lpgFLKqvE'),
(17, 'Ko-soto-gake', 'judo', 'Throws', 'Minor outer hook', 'https://www.youtube.com/watch?v=jl99iUTlIVY'),
(18, 'Tsuri-goshi', 'judo', 'Throws', 'Lifting hip throw', 'https://www.youtube.com/results?search_query=Tsuri-goshi'),
(19, 'Yoko-otoshi', 'judo', 'Throws', 'Side drop', 'https://www.youtube.com/watch?v=Uu9XXHHYMRo'),
(20, 'Ashi-guruma', 'judo', 'Throws', 'Leg wheel', 'https://www.youtube.com/watch?v=c7pqq2sC8Ng'),
(21, 'Hane-goshi', 'judo', 'Throws', 'Spring hip throw', 'https://www.youtube.com/watch?v=n7GP5S41Os8'),
(22, 'Harai-tsurikomi-ashi', 'judo', 'Throws', 'Sweeping drawing ankle throw', 'https://www.youtube.com/watch?v=23ATiD6TsZs'),
(23, 'Tomoe-nage', 'judo', 'Throws', 'Circle throw', 'https://www.youtube.com/watch?v=-euJliq9XcY'),
(24, 'Kata-guruma', 'judo', 'Throws', 'Shoulder wheel', 'https://www.youtube.com/watch?v=3q110EX_1wY'),
(25, 'Sumi-gaeshi', 'judo', 'Throws', 'Corner reversal', 'https://www.youtube.com/watch?v=0BuqVnafVSg'),
(26, 'Tani-otoshi', 'judo', 'Throws', 'Valley drop', 'https://www.youtube.com/watch?v=wS9pM3y8YH4'),
(27, 'Hane-makikomi', 'judo', 'Throws', 'Spring wraparound throw', 'https://www.youtube.com/watch?v=wG5kQT7M8is'),
(28, 'Sukui-nage', 'judo', 'Throws', 'Scoop throw', 'https://www.youtube.com/watch?v=gz0CnjKm3ZM'),
(29, 'Utsuri-goshi', 'judo', 'Throws', 'Hip shift', 'https://www.youtube.com/watch?v=E81rR10wfXU'),
(30, 'O-guruma', 'judo', 'Throws', 'Major wheel', 'https://www.youtube.com/watch?v=ujxkj6EJSb0'),
(31, 'Soto-makikomi', 'judo', 'Throws', 'Outer wraparound throw', 'https://www.youtube.com/watch?v=BcfGFR1CWss'),
(32, 'Uki-otoshi', 'judo', 'Throws', 'Floating drop', 'https://www.youtube.com/watch?v=d8Cmcfvh7M8'),
(33, 'O-soto-guruma', 'judo', 'Throws', 'Major outer wheel', 'https://www.youtube.com/watch?v=CdjR9VyQaL0'),
(34, 'Uki-waza', 'judo', 'Throws', 'Floating technique', 'https://www.youtube.com/watch?v=JtB79Ma4htw'),
(35, 'Yoko-wakare', 'judo', 'Throws', 'Side separation', 'https://www.youtube.com/watch?v=fWlPaLwvBV8'),
(36, 'Yoko-guruma', 'judo', 'Throws', 'Side wheel', 'https://www.youtube.com/watch?v=BYD0IRZPlxI'),
(37, 'Ushiro-goshi', 'judo', 'Throws', 'Rear hip throw', 'https://www.youtube.com/watch?v=sqQ4tr3iERE'),
(38, 'Ura-nage', 'judo', 'Throws', 'Rear throw', 'https://www.youtube.com/watch?v=4hzlipey14I'),
(39, 'Sumi-otoshi', 'judo', 'Throws', 'Corner drop', 'https://www.youtube.com/watch?v=CL6tPu1Khc4'),
(40, 'Yoko-gake', 'judo', 'Throws', 'Side hook', 'https://www.youtube.com/watch?v=YntUIakl428'),
(41, 'Osoto-gaeshi', 'judo', 'Throws', 'Major outer reap counter', 'https://www.youtube.com/watch?v=FVHAn45Gd6w'),
(42, 'Harai-goshi-gaeshi', 'judo', 'Throws', 'Sweeping hip counter', 'https://www.youtube.com/watch?v=t2hgLa7BZbE'),
(43, 'Uchi-mata-gaeshi', 'judo', 'Throws', 'Inner thigh counter', 'https://www.youtube.com/watch?v=rzOSmEiuVtg'),
(44, 'Tawara-gaeshi', 'judo', 'Throws', 'Rice bag reversal', 'https://www.youtube.com/watch?v=zORVnrrPnmM'),
(45, 'Osoto-makikomi', 'judo', 'Throws', 'Major outer wraparound', 'https://www.youtube.com/watch?v=-CZO8Mj5cA8'),
(46, 'Harai-makikomi', 'judo', 'Throws', 'Sweeping wraparound', 'https://www.youtube.com/watch?v=MWd5CYkm2zI'),
(47, 'Uchi-mata-makikomi', 'judo', 'Throws', 'Inner thigh wraparound', 'https://www.youtube.com/watch?v=AJy_muVxkaE'),
(48, 'Kesa-gatame', 'judo', 'Pins', 'Scarf hold', 'https://www.youtube.com/watch?v=3UnJa3bn0h8'),
(49, 'Kata-gatame', 'judo', 'Pins', 'Shoulder hold', 'https://www.youtube.com/watch?v=TFClghvGD9w'),
(50, 'Kami-shiho-gatame', 'judo', 'Pins', 'Upper four corner hold', 'https://www.youtube.com/watch?v=2evEh7OBnBg'),
(51, 'Yoko-shiho-gatame', 'judo', 'Pins', 'Side four corner hold', 'https://www.youtube.com/watch?v=1GJn6OEyuO4'),
(52, 'Tate-shiho-gatame', 'judo', 'Pins', 'Lengthwise four corner hold', 'https://www.youtube.com/watch?v=XjWzNxlKH1M'),
(53, 'Hadaka-jime', 'judo', 'Chokes', 'Rear naked choke', 'https://www.youtube.com/watch?v=9f0n8jez7iA'),
(54, 'Okuri-eri-jime', 'judo', 'Chokes', 'Sliding lapel choke', 'https://www.youtube.com/watch?v=whiX-aety6o'),
(55, 'Kata-ha-jime', 'judo', 'Chokes', 'Single wing choke', 'https://www.youtube.com/watch?v=yaTGgRjnwB8'),
(56, 'Gyaku-juji-jime', 'judo', 'Chokes', 'Reverse cross choke', 'https://www.youtube.com/watch?v=t3tQriIPdlI'),
(57, 'Nami-juji-jime', 'judo', 'Chokes', 'Normal cross choke', 'https://www.youtube.com/watch?v=k2cHry9HByQ'),
(58, 'Ude-garami', 'judo', 'Armlocks', 'Entangled armlock', 'https://www.youtube.com/watch?v=AIlTvZb4RlE'),
(59, 'Ude-hishigi-juji-gatame', 'judo', 'Armlocks', 'Cross armlock (juji gatame)', 'https://www.youtube.com/watch?v=OWgSOlCuMXw'),
(60, 'Ude-hishigi-ude-gatame', 'judo', 'Armlocks', 'Arm armlock', 'https://www.youtube.com/watch?v=SBf0aTma1VI'),
(61, 'Ude-hishigi-hiza-gatame', 'judo', 'Armlocks', 'Knee armlock', 'https://www.youtube.com/watch?v=H2HtAJdiJcE'),
(62, 'Closed guard', 'bjj', 'Guards', 'Opponent between your legs, feet crossed', 'https://www.youtube.com/watch?v=kPZh0ZZyZj0'),
(63, 'Open guard', 'bjj', 'Guards', 'Feet on hips/biceps, controlling distance', 'https://www.youtube.com/watch?v=xIVAPf44K0Q'),
(64, 'Half guard', 'bjj', 'Guards', 'One leg trapped between yours', 'https://www.youtube.com/watch?v=E8x1Cva8hJ8'),
(65, 'De la Riva guard', 'bjj', 'Guards', 'Hook on outside of lead leg', 'https://www.youtube.com/watch?v=18Wle1vr5PI'),
(66, 'Spider guard', 'bjj', 'Guards', 'Feet on biceps, sleeve grips', 'https://www.youtube.com/watch?v=5ciTwCNs8uM'),
(67, 'Butterfly guard', 'bjj', 'Guards', 'Hooks inside opponent thighs', 'https://www.youtube.com/watch?v=GTZwGn7HVRE'),
(68, 'Triangle choke', 'bjj', 'Chokes', 'Figure-four choke with legs', 'https://www.youtube.com/watch?v=kTW9tXjh-NY'),
(69, 'Rear naked choke', 'bjj', 'Chokes', 'Arm across throat from back', 'https://www.youtube.com/watch?v=KW2RvtWgBxU'),
(70, 'Guillotine choke', 'bjj', 'Chokes', 'Head and arm choke from front', 'https://www.youtube.com/watch?v=KrZn5eJ-j4Q'),
(71, 'Arm triangle', 'bjj', 'Chokes', 'Head and arm choke from side', 'https://www.youtube.com/watch?v=52NZhOpA2YE'),
(72, 'Armbar', 'bjj', 'Armlocks', 'Hyperextend elbow joint', 'https://www.youtube.com/watch?v=bkMUBlqh27g'),
(73, 'Kimura', 'bjj', 'Armlocks', 'Figure-four shoulder lock', 'https://www.youtube.com/watch?v=-OoSucz81BM'),
(74, 'Americana', 'bjj', 'Armlocks', 'Bent arm shoulder lock', 'https://www.youtube.com/watch?v=5M1wkbaOYUM'),
(75, 'Omoplata', 'bjj', 'Armlocks', 'Shoulder lock with legs', 'https://www.youtube.com/watch?v=dpuKJPsq84g'),
(76, 'Heel hook', 'bjj', 'Leg locks', 'Rotational knee/ankle lock', 'https://www.youtube.com/watch?v=hNTsYUShvLU'),
(77, 'Kneebar', 'bjj', 'Leg locks', 'Hyperextend knee joint', 'https://www.youtube.com/watch?v=CoUv2kmQ7_A'),
(78, 'Ankle lock', 'bjj', 'Leg locks', 'Compression ankle/Achilles lock', 'https://www.youtube.com/watch?v=rTUFu5VJQYw'),
(79, 'Calf slicer', 'bjj', 'Leg locks', 'Compression lock on calf', 'https://www.youtube.com/watch?v=9EwRjvWPBZE'),
(80, 'Bridge and roll escape', 'bjj', 'Escapes', 'Escape from mount using bridge', 'https://www.youtube.com/watch?v=pbbsdA3MMLk'),
(81, 'Elbow-knee escape', 'bjj', 'Escapes', 'Escape from mount using shrimp', 'https://www.youtube.com/watch?v=8yo1SIJ8RYY'),
(82, 'Guard recovery', 'bjj', 'Escapes', 'Re-establish guard from side control', 'https://www.youtube.com/watch?v=T9ckJr1MV7Q'),
(83, 'Turtle escape', 'bjj', 'Escapes', 'Escape from turtle position', 'https://www.youtube.com/watch?v=i08uQgulYmc'),
(84, 'Mount', 'bjj', 'Positions', 'Sitting on opponent''s chest/hips', 'https://www.youtube.com/watch?v=Wy6Si0FuQaU'),
(85, 'Back control', 'bjj', 'Positions', 'Behind opponent with hooks', 'https://www.youtube.com/watch?v=clM9dN8bBH4'),
(86, 'Side control', 'bjj', 'Positions', 'Perpendicular control across chest', 'https://www.youtube.com/watch?v=nDbHQPBvQvQ')
on conflict (id) do nothing;
